# Official Ubuntu Image
FROM ubuntu:18.04

# Set Working Directory
WORKDIR /home/

# Add contents of current directory to the home directory
ADD . /home/

# cat the test file in the directory
RUN cat test.txt